-- 
title: mini project deliverable 2
--
# Task 1: Process and and summarize your data #

1.1 First, write out the 4 research questions you defined in milestone 1 were. This will guide your work through milestone 2:

    FILL_THIS_IN
    FILL_THIS_IN
    FILL_THIS_IN
    FILL_THIS_IN
    
1.2 Now, for each of your four research questions, choose one task from options 1-4 (summarizing), and one other task from 4-8 (graphing). 
You should have 2 tasks done for each research question (8 total). 
Make sure it makes sense to do them! (e.g. don’t use a numerical variables for a task that needs a categorical variable.). 
Comment on why each task helps (or doesn’t!) answer the corresponding research question.

Ensure that the output of each operation is printed!

  Summarizing:

    Compute the range, mean, and two other summary statistics of one numerical variable across the groups of one categorical variable from your data.
    Compute the number of observations for at least one of your categorical variables. Do not use the function table()!
    Create a categorical variable with 3 or more groups from an existing numerical variable. You can use this new variable in the other tasks! An example: age in years into “child, teen, adult, senior”.
    Based on two categorical variables, calculate two summary statistics of your choosing.

  Graphing:

    Create a graph out of summarized variables that has at least two geom layers.
    Create a graph of your choosing, make one of the axes logarithmic, and format the axes labels so that they are “pretty” or easier to read.
    Make a graph where it makes sense to customize the alpha transparency.
    Create 3 histograms out of summarized variables, with each histogram having different sized bins. Pick the “best” one and explain why it is the best.

  Make sure it’s clear what research question you are doing each operation for!
  
1.3 Based on the operations that you’ve completed, how much closer are you to answering your research questions? 
Think about what aspects of your research questions remain unclear. Can your research questions be refined, now that you’ve investigated your data a bit more? 
Which research questions are yielding interesting results?

# Task 2: Tidy your data # 
In this task, we will do several exercises to reshape our data. The goal here is to understand how to do this reshaping with the tidyr package.

A reminder of the definition of tidy data:

    Each row is an observation
    Each column is a variable
    Each cell is a value

Tidying data is sometimes necessary because it can simplify computation. Other times it can be nice to organize data so that it can be easier to understand when read manually.

2.1 Based on the definition above, can you identify if your data is tidy or untidy? 
Go through all your columns, or if you have >8 variables, just pick 8, and explain whether the data is untidy or tidy.

2.2 Now, if your data is tidy, untidy it! Then, tidy it back to it’s original state.

If your data is untidy, then tidy it! Then, untidy it back to it’s original state.

Be sure to explain your reasoning for this task. Show us the “before” and “after”.

2.3 Now, you should be more familiar with your data, and also have made progress in answering your research questions. 
Based on your interest, and your analyses, pick 2 of the 4 research questions to continue your analysis in milestone 3, and explain your decision.
Try to choose a version of your data that you think will be appropriate to answer these 2 questions in milestone 3. 
Use between 4 and 8 functions that we’ve covered so far (i.e. by filtering, cleaning, tidy’ing, dropping irrelvant columns, etc.).
When you are done, knit an md file. This is what we will mark! Make sure to open it and check that everything has knitted correctly before submitting your tagged release.
